# Generated by Django 4.0.6 on 2023-08-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='extra_data',
            field=models.TextField(blank=True, help_text='bisa diisi untuk melengkapi request yang diterima', null=True),
        ),
        migrations.AddField(
            model_name='debit',
            name='via',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='kredit',
            name='extra_data',
            field=models.TextField(blank=True, help_text='bisa diisi untuk melengkapi request yang diterima', null=True),
        ),
        migrations.AddField(
            model_name='kredit',
            name='via',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API')], default='web', max_length=10),
        ),
    ]
