# Generated by Django 4.0.6 on 2023-08-26 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_remove_kelas_ruangan_kelas_sekolah'),
        ('tabungan', '0002_debit_extra_data_debit_via_kredit_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=220)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('id_perangkat', models.CharField(help_text='ID dapat ditemukan pada bagian bawah perangkat', max_length=150, unique=True)),
                ('jenis', models.CharField(blank=True, help_text='Jenis dapat ditemukan pada bagian bawah perangkat, jika tidak ditemukan bisa dikosongkan', max_length=150, null=True)),
                ('sekolah', models.ForeignKey(help_text='Pilih jika tenan berada pada sekolah mana', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.sekolah')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
