# Generated by Django 4.0.6 on 2023-09-05 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0003_tenan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no_transaksi_tenan', models.CharField(help_text='no ini didapatkan dari sistem pembayaran tenan', max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kredit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabungan.kredit')),
                ('tenan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabungan.tenan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
